Bump Pandas version bound 2
Bump version bound again because in 1.2.0 we saw:
```
ERROR: test_create_table_will_return_empty_result_set (python.pysql.driver_tests.PySQLCoreTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/niallegan/universe/cmdexec/clients/../../[qa/test/bi/python/pysql/driver_tests.py](http://qa/test/bi/python/pysql/driver_tests.py)", line 183, in test_create_table_will_return_empty_result_set
    self.assertEqual(cursor.fetchall(), [])
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/databricks/sql/client.py", line 359, in fetchall
    return self.active_result_set.fetchall()
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/databricks/sql/client.py", line 616, in fetchall
    return self._convert_arrow_table(self.fetchall_arrow())
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/databricks/sql/client.py", line 557, in _convert_arrow_table
    df = table_renamed.to_pandas(
  File "pyarrow/array.pxi", line 757, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1748, in pyarrow.lib.Table._to_pandas
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 789, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1130, in _table_to_blocks
    return [_reconstruct_block(item, columns, extension_columns)
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1130, in <listcomp>
    return [_reconstruct_block(item, columns, extension_columns)
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 749, in _reconstruct_block
    pd_ext_arr = pandas_dtype.__from_arrow__(arr)
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pandas/core/arrays/integer.py", line 121, in __from_arrow__
    return IntegerArray._concat_same_type(results)
  File "/Users/niallegan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pandas/core/arrays/masked.py", line 271, in _concat_same_type
    data = np.concatenate([x._data for x in to_concat])
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

Running full integration test suite to completion with Pandas 1.3.0