Increase version bound for Pandas + release 2.0.1
Users encountering failures with message:
```
After an update in databricks-sql-connector, the query s failing with the following error:-
module 'pandas' has no attribute 'Float32Dtype'  but succeeds with version 1.0.2 in DBR version 7.3 PFA
```
Looking at [https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data), it seems we need to use Pandas 1.2.0+

User verified that upgrading Pandas to 1.2.0 fixed the issue