Increase version bound for Pandas + release 2.0.1
## What changes are proposed in this pull request?
   See http://go/pr-description for tips on what to write here
   New to Databricks? See http://go/pr-process

   [NEW] Please review if shiproom approval is required.
   See the Shiproom section below for details.
Users encountering failures with message:
```
After an update in databricks-sql-connector, the query s failing with the following error:-
module 'pandas' has no attribute 'Float32Dtype'  but succeeds with version 1.0.2 in DBR version 7.3 PFA
```
Looking at [ttps://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data), it seems we need to use Pandas 1.2.0+
## How is this tested?
  - Added unit or integration tests? Please mention them here.
  - Performed manual testing? Please describe your testing procedure.
  - Was testing unnecessary or not possible? Please explain why.
User verified that upgrading Pandas to 1.2.0 fixed the issue
## How is this feature monitored?
  - Did you add usage logs or metrics? Please mention them here.
  - Create dashboards or monitoring notebooks? Please link them here.
  - See http://go/obs/user for docs on our observability tools.

#### Approvals

#### [NEW] Shiproom

  - [ ] A "material change" covering this PR exists in http://go/engshiproom: `<CHANGE_ID>`

  - [ ] Change is **NOT** a “material change”
  - [ ] Change **IS** a “material change” of low / medium risk
  - [ ] Change **IS** a “material change” of high risk needing Shiproom review

#### Security implications
#165317 is resolved by databricks/master.