We see the following errors in the sqlalchemy test suite after merging server-side parameters
FAILED test/test_dialect_compliance.py::DateTest_databricks+databricks::test_null - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DateTest_databricks+databricks::test_null_bound_comparison - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DateTimeMicrosecondsTest_databricks+databricks::test_null - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DateTimeMicrosecondsTest_databricks+databricks::test_null_bound_comparison - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DateTimeTest_databricks+databricks::test_null - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DateTimeTest_databricks+databricks::test_null_bound_comparison - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape[/slashes/] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) 
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape[dot.s] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNBOUND_SQL_PARAMETER] Found the unbound parameter: dot. Please, fix `args` and provide a mapping of the parameter to a SQL literal.; line 3 pos 21
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape[more/slashes] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNBOUND_SQL_PARAMETER] Found the unbound parameter: more. Please, fix `args` and provide a mapping of the parameter to a SQL literal.; line 3 pos 21
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape[q?marks] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) 
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape_expanding[/slashes/] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) 
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape_expanding[dot.s] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNBOUND_SQL_PARAMETER] Found the unbound parameter: dot. Please, fix `args` and provide a mapping of the parameter to a SQL literal.; line 3 pos 23
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape_expanding[more/slashes] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNBOUND_SQL_PARAMETER] Found the unbound parameter: more. Please, fix `args` and provide a mapping of the parameter to a SQL literal.; line 3 pos 23
FAILED test/test_dialect_compliance.py::DifficultParametersTest_databricks+databricks::test_standalone_bindparam_escape_expanding[q?marks] - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) 
FAILED test/test_dialect_compliance.py::IntegerTest_databricks+databricks::test_huge_int - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.DatabaseError) [INVALID_PARAMETER_MARKER_VALUE.INVALID_VALUE_FOR_DATA_TYPE] An invalid parameter mapping was provided: the value '1376537018368127' for parameter 'integer_data' cannot be cast to INT because it is malformed.
FAILED test/test_dialect_compliance.py::IsOrIsNotDistinctFromTest_databricks+databricks::test_is_or_is_not_distinct_from[both_null] - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::IsOrIsNotDistinctFromTest_databricks+databricks::test_is_or_is_not_distinct_from[one_null_first] - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::IsOrIsNotDistinctFromTest_databricks+databricks::test_is_or_is_not_distinct_from[one_null_second] - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::NumericTest_databricks+databricks::test_float_as_decimal - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::NumericTest_databricks+databricks::test_float_coerce_round_trip - AssertionError: 15.75629997253418 != 15.7563
FAILED test/test_dialect_compliance.py::NumericTest_databricks+databricks::test_numeric_null_as_decimal - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::NumericTest_databricks+databricks::test_numeric_null_as_float - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::TextTest_databricks+databricks::test_text_null_strings - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::TimeMicrosecondsTest_databricks+databricks::test_null - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::TimeTest_databricks+databricks::test_null - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::UnicodeTextTest_databricks+databricks::test_null_strings_text - ValueError: Parameter type cannot be inferred
FAILED test/test_dialect_compliance.py::UnicodeVarcharTest_databricks+databricks::test_null_strings_varchar - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_contains_autoescape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_contains_autoescape_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_contains_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_contains_unescaped - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_endswith_autoescape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_endswith_autoescape_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_endswith_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_endswith_sqlexpr - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_endswith_unescaped - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_not_regexp_match - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[(b|c)-expected5] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[9cde-expected3] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[^(b|c)-expected6] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[^a-expected4] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[^abc-expected2] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[a.cde-expected0] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_match[abc-expected1] - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_regexp_replace - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_startswith_autoescape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_startswith_autoescape_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_startswith_escape - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_startswith_sqlexpr - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::LikeFunctionsTest_databricks+databricks::test_startswith_unescaped - ValueError: Parameter type cannot be inferred
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_composed_int - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_composed_int_desc - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_composed_multiple - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_group_by_composed - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_plain - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0
ERROR test/test_dialect_compliance.py::OrderByLabelTest_databricks+databricks::test_plain_desc - sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `x` cannot be resolved. Did you mean one of the following? [`id`, `data`].; line 1 pos 0

Signed-off-by: Jesse Whitehouse <jesse.whitehouse@databricks.com>